name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: developmentOptimizeJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: minecraft
        uses: mcenv/setup-minecraft@v3
        with:
          version: "snapshot"
      - run: |
          cd test
          java -jar ../build/libs/mch.jar --mc=$MINECRAFT
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.minecraft.outputs.version }}
          path: test/mch-results.json
